name: Builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
        choco install cmake
        choco install ninja
        choco install llvm

    - name: Configure and build
      run: |
        cmake --preset win64-release
        cmake --build build
      
      
  unix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
       sudo apt-get update
       sudo apt-get install -y cmake
       sudo apt-get install -y clang
       sudo apt-get install -y ninja-build

    - name: Install libs
      run: sudo apt-get install -y libtbb-dev

    - name: Configure and build
      run: |
        cmake --preset linux64-release
        cmake --build build
