name: Make release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'A version tag'
        default: '0.0'
        required: true
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The tag is ${{ inputs.tag }}
