name: Ubuntu
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install gcc
      run: sudo apt install gcc-10

    - name: CMake Configure
      run: cmake -S . -B build/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: CMake Build
      shell: bash
      run: cmake --build build/ --config $BUILD_TYPE
