name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install tbb
      run: sudo apt install libtbb-dev
    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_CONFIG=Release
    - name: Build
      run: cmake --build build
