name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake -S . -B build -DCMAKE_BUILD_CONFIG=Release
    - name: build
      run: cmake --build build
