name: Unix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install tbb
      run: sudo install libtbb-dev

    - name: Run build script
      run: sh ./scripts/build_unix.sh
